USE pisuena_cotizador;

CREATE TABLE IF NOT EXISTS FAMILIAS (
	ID_FAMILIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE TINYTEXT UNIQUE NOT NULL,
    DESCRIPCION TEXT DEFAULT "UNDEFINED",
    STATUS ENUM("ACTIVO", "INACTIVO", "DESCONOCIDO") DEFAULT "ACTIVO",
    FECHA_PUBLICACION DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORIAS (
	ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE TINYTEXT UNIQUE NOT NULL,
    DESCRIPCION TEXT DEFAULT "UNDEFINED",
    STATUS ENUM("ACTIVO", "INACTIVO", "DESCONOCIDO") DEFAULT "ACTIVO",
    FECHA_PUBLICACION DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SUBCATEGORIAS (
	ID_SUBCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE TINYTEXT UNIQUE NOT NULL,
    DESCRIPCION TEXT DEFAULT "UNDEFINED",
    STATUS ENUM("ACTIVO", "INACTIVO", "DESCONOCIDO") DEFAULT "ACTIVO",
    FECHA_PUBLICACION DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATALOGO(
	ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO TINYTEXT UNIQUE NOT NULL,
    SKU TINYTEXT DEFAULT "UNDEFINED ",
    NOMBRE MEDIUMTEXT UNIQUE NOT NULL,
    DESCRIPCION TEXT DEFAULT "UNDEFINED",
    PESO DECIMAL(12,2) DEFAULT 0,
    ANCHO DECIMAL(12,2) DEFAULT 0,
    LARGO DECIMAL(12,2) DEFAULT 0,
    ALTO DECIMAL(12,2) DEFAULT 0,
    MODELO TINYTEXT DEFAULT "UNDEFINED",
    UNIDAD ENUM("PZ","CJA","KG","LT","G") DEFAULT "PZ",
    NUMERO_PROVEEDOR TINYTEXT DEFAULT "UNDEFINED",
    MARCA TINYTEXT DEFAULT "UNDEFINED",
    ID_FAMILIA INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    ID_SUBCATEGORIA INT NOT NULL,
    IMAGE MEDIUMBLOB DEFAULT NULL,
    STATUS ENUM("ACTIVO", "INACTIVO", "DESCONOCIDO") DEFAULT "ACTIVO",
    FECHA_PUBLICACION DATE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_FAMILIA) REFERENCES FAMILIAS (ID_FAMILIA),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA),
    FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIAS (ID_SUBCATEGORIA)
);

CREATE TABLE IF NOT EXISTS REGISTROS(
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE +
    CORREO +
    CONTRASENA +
    DIRECCION
    TELEFONO +
    NOMBRE_EMPRESA
    FECHA_PUBLICACION DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COTIZACIONES(
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE +
    CORREO +
    CONTRASENA +
    DIRECCION
    TELEFONO +
    NOMBRE_EMPRESA
    ID_REGISTRO DEFAULT NULL
    JSON_ARTICULOS
    FECHA_PUBLICACION DATE DEFAULT CURRENT_TIMESTAMP
);